[package]
name = "shoogah"
version = "0.1.0"
authors = ["Jose Colon Rodriguez <jec.rod@gmail.com>"]
edition = "2018"
description = "Add some syntactic 'shoogah' to Rust."

[dependencies]
as_bool = { path = "../as_bool" }
shoogah_macros = { path = "../shoogah_macros" }
